### ISSUE TITLE
Memoria - Técnicas y herramientas

### ISSUE THREAD

**Issue by Joaquin-GM** [Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software#39]

**Comment by Joaquin-GM** [comment]
Primera versión de la sección finalizada.
Quedan pendientes las url de los informes generados una vez todas las herramientas estén funcionando.
Consultar los cambios de versiones propuestos en el siguiente Sprint Review.

**Comment by clopezno** [comment]
Buen trabajo.  Se continua el estilo de calidad de la primera iteración del TFG.
En agilidad hay un dicho parecido a este:" _Es muy importante plantar el árbol pero es aún más importante seguir regándolo_"
Adjunto un pdf con algunos comentarios de revisión de las secciones de técnicas y herramientas y aspectos relevante
[memoriarevclopezno.pdf](https://github.com/Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software/files/8340139/memoriarevclopezno.pdf)
s
