### ISSUE TITLE
Memoria - Ajuste Introducción y objetivos

### ISSUE THREAD

**Issue by Joaquin-GM** [Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software#44]
Abreviar introducción tanto en castellano como en inglés.
Reordenar los objetivos, poniendo previamente los del proyecto ya existente ya que tiene más lógica y es más fácil de entender así.

**Comment by clopezno** [comment]
Adjunto un pdf con comentarios de revisión del documento de memoria del TFG a fecha del viernes 4/03.

Revísalo y lo comentamos en la siguiente reunión.

[memoria-revclopezno.pdf](https://github.com/Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software/files/8196168/memoria-revclopezno.pdf)
