### ISSUE TITLE
Memoria - Correcciones

### ISSUE THREAD

**Issue by Joaquin-GM** [Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software#56]

**Comment by Joaquin-GM** [comment]
Correcciones indicadas en:

[memoriarevclopezno_2.pdf](https://github.com/Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software/files/8520982/memoriarevclopezno_2.pdf)

**Comment by clopezno** [comment]
Gran trabajo. Adjunto la versión corregida de la memoria y firmada digitalmente.
[memoriaJoaquinV2firmada.pdf](https://github.com/Joaquin-GM/GII_O_MA_19.07-Comparador-de-metricas-de-evolucion-en-repositorios-Software/files/8889238/memoriaJoaquinV2firmada.pdf)
